import { createClient } from '@/lib/supabase/server'
import { NextResponse } from 'next/server'
import { sendEmail, emailTemplates } from '@/lib/email'
import { createApiClient } from '@/lib/supabase/api'

export async function POST(request: Request) {
    try {
        const supabase = await createClient()
        const apiClient = createApiClient()

        // Verify the user is authenticated
        const { data: { user }, error: authError } = await supabase.auth.getUser()
        if (authError || !user) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
        }

        // Check if user is already verified
        if (user.email_confirmed_at) {
            return NextResponse.json({
                error: 'Email is already verified',
                alreadyVerified: true
            }, { status: 400 })
        }

        // Get user profile to check role and get display name
        const { data: profile } = await apiClient
            .from('profiles')
            .select('role, display_name, is_verified')
            .eq('id', user.id)
            .single()

        // Only clients need verification
        if (profile && profile.role !== 'client') {
            return NextResponse.json({
                error: 'Verification is only required for clients',
                notRequired: true
            }, { status: 400 })
        }

        // Generate verification link using Supabase
        // Use resend with type 'signup' - this works for existing unverified users
        // and generates the proper email verification token
        const redirectUrl = `${process.env.NEXT_PUBLIC_APP_URL || 'https://negoempire.vercel.app'}/auth/verify-email`

        // Resend verification email - generates verification token
        // IMPORTANT: Disable Supabase email templates in dashboard to prevent duplicate emails:
        // Supabase Dashboard → Authentication → Email Templates → Disable "Confirm signup"
        const { error: resendError } = await supabase.auth.resend({
            type: 'signup',
            email: user.email!,
            options: {
                emailRedirectTo: redirectUrl,
            },
        })

        if (resendError) {
            console.error('[Send Verification Email] Failed to resend verification:', resendError)
            return NextResponse.json({
                error: 'Failed to generate verification link. Please try again.',
                details: resendError.message
            }, { status: 500 })
        }

        // Send our custom verification email
        // Note: The actual verification token is generated by Supabase's resend above
        // Users will receive Supabase's email with the token UNLESS email templates are disabled
        // Our custom email uses the redirect URL - users can click it and Supabase will handle the token
        const emailResult = await sendEmail(
            user.email!,
            emailTemplates.verifyEmail(
                profile?.display_name || user.user_metadata?.full_name || 'User',
                redirectUrl
            )
        )

        if (!emailResult.success) {
            console.error('[Send Verification Email] Failed to send custom email:', emailResult.error)
            // Supabase email was sent via resend, so we still return success
            // But log the custom email failure for debugging
        }

        return NextResponse.json({
            success: true,
            message: 'Verification email sent successfully'
        })
    } catch (error) {
        console.error('[Send Verification Email] Unexpected error:', error)
        return NextResponse.json({
            error: 'An unexpected error occurred',
            details: error instanceof Error ? error.message : 'Unknown error'
        }, { status: 500 })
    }
}
